Terraform, EC2 Container Service (ECS) and Docker
=================================================

This example demos how Terraform provision AWS instances, based on *"Infrastructure As Code"* principle.

Under this directory, after you run *"terraform apply"* on these Terraform configuration, a new AWS ECS will be created.

Have Terraform installed. Create a file *"terraform.tfvars"* which including AWS access and secret keys (terraform.tfvars.sample file):

[source.console]
----
access_key = "This is AWS account's Access Key"
secret_key = "This is AWS account's Secret Key"
----

==== Verify provision plan 
[source.console]
----
12:29:09 𝜆 terraform plan -var 'key_name=aws-key' -var 'key_path=/Users/terrence/.ssh/aws-key.pem'
...
----

==== Run 
Create AWS instance, install ECS agent and start Docker container:

[source.console]
----
12:29:09 𝜆 terraform apply -var 'key_name=aws-key' -var 'key_path=/Users/terrence/.ssh/aws-key.pem'
...
----

==== Destroy all resource

[source.console]
----
11:42:29 𝜆 terraform destroy -var 'key_name=aws-key' -var 'key_path=/Users/terrence/.ssh/aws-key.pem'
...
----

==== Check Docker application status

[source.console]
----
09:13:57 𝜆 ecs-cli ps
Name                                                        State    Ports                         TaskDefinition
7e4d36f1-b016-487a-9dfc-f808c995a3f6/hello-world-container  RUNNING  54.206.39.253:80->80/tcp      hello-world-task:5
----

==== Add and run a new Docker application

[source.console]
----
𝜆 ecs-cli compose --project-name camel-spring --file docker-compose.yml create
INFO[0000] Using ECS task definition                     TaskDefinition=ecscompose-camel-spring:1

𝜆 ecs-cli compose --project-name camel-spring --file docker-compose.yml service up
INFO[0000] Using ECS task definition                     TaskDefinition=ecscompose-camel-spring:2
INFO[0000] Created an ECS service                        service=ecscompose-service-camel-spring taskDefinition=ecscompose-camel-spring:2
INFO[0000] Updated ECS service successfully              desiredCount=1 serviceName=ecscompose-service-camel-spring
INFO[0000] Describe ECS Service status                   desiredCount=1 runningCount=0 serviceName=ecscompose-service-camel-spring
INFO[0030] Describe ECS Service status                   desiredCount=1 runningCount=0 serviceName=ecscompose-service-camel-spring
INFO[0045] ECS Service has reached a stable state        desiredCount=1 runningCount=1 serviceName=ecscompose-service-camel-spring

𝜆 ecs-cli ps
Name                                                        State                  Ports                         TaskDefinition
4f3101ca-0ed6-460b-8c1e-11d4cee912b1/hello-world-container  RUNNING                54.206.39.253:80->80/tcp      hello-world-task:5
912d879b-9803-4a7e-99eb-1b747fbdc592/demo                   RUNNING                54.206.39.253:8080->8080/tcp  ecscompose-camel-spring:2
----

==== Verify Docker applications

Go to URLs: 

http://terraform-ecs-elb-223796138.ap-southeast-2.elb.amazonaws.com
http://terraform-ecs-elb-223796138.ap-southeast-2.elb.amazonaws.com:8080/hawtio/index.html

terraform-ecs-elb-223796138.ap-southeast-2.elb.amazonaws.com is the interface on Load Balancer.

==== Stop Docker application service in ECS

[source.console]
----
𝜆 ecs-cli compose --project-name camel-spring --file docker-compose.yml service rm
INFO[0000] Updated ECS service successfully              desiredCount=0 serviceName=ecscompose-service-camel-spring
INFO[0000] ECS Service has reached a stable state        desiredCount=0 runningCount=0 serviceName=ecscompose-service-camel-spring
INFO[0000] Deleted ECS service                           service=ecscompose-service-camel-spring
INFO[0000] ECS Service has reached a stable state        desiredCount=0 runningCount=0 serviceName=ecscompose-service-camel-spring
----


References
----------
- Terraform and AWS ECS - Transforming infrastructure provision into programming code, https://prezi.com/flhqxtm-r4ys/terraform-and-aws-ecs/
- A Comprehensive Guide to Building a Scalable Web App on Amazon Web Services - Part 1, https://www.airpair.com/aws/posts/building-a-scalable-web-app-on-amazon-web-services-p1
- AWS Tips I Wish I'd Known Before I Started, https://wblinks.com/notes/aws-tips-i-wish-id-known-before-i-started/
- Four Ways to Collect Docker Logs in Sumo Logic, https://www.sumologic.com/blog-using-sumo/four-ways-to-collect-docker-logs-in-sumo-logic/
- Sumo Logic Collector for Docker, https://github.com/SumoLogic/sumologic-collector-docker, https://hub.docker.com/r/sumologic/collector/
- ECS CLI Command Line Reference, http://docs.aws.amazon.com/AmazonECS/latest/developerguide/ECS_CLI_reference.html
- Amazon EC2 Container Service (Amazon ECS) Command Line Reference, http://docs.aws.amazon.com/cli/latest/reference/ecs/
- Setup local / private Docker Registry, http://slides.com/victororlov/docker-registry-presentation, https://github.com/fforloff/docker-registry-presentation


Copying
-------
Copyright © 2016 - Terrence Miao. Free use of this software is granted under the terms of the GNU General Public License version 3 (GPLv3).
