Step by step run ElasticSearch / Kibana Docker images
=====================================================

This project including instructions to run ElasticSearch / Kibana Docker images on localhost.

- Create shared volumes / mounted directories
[source.console]
----
terrence@muffler ~/elasticsearch
13:07:32 189 ğœ† mkdir data plugins

iterrence@muffler ~/kibana
13:07:32 189 ğœ† mkdir installedPlugins
----

- Copy ALL exiting, installed plugins from to shared, mounted directory
[source.console]
----
terrence@muffler ~/elasticsearch
13:07:32 190 ğœ† cp -a /usr/local/elasticsearch/plugins/* plugins

13:07:32 191 ğœ† ls -1 plugins/
dejaVu
head
kopf

terrence@muffler ~/kibana
13:07:32 190 ğœ† cp -a /usr/local/kibana/installedPlugins/* installedPlugins

13:07:32 191 ğœ† ls -1 installedPlugins/
sense
----

- CORS

To make sure you enable CORS settings for your ElasticSearch instance, add the following lines in the ES configuration file - *elasticsearch.yml*

[source.console]
----
http.cors.enabled: true
http.cors.allow-origin: "/.*/"
http.cors.allow-credentials: true
http.cors.allow-headers: "Authorization, X-Requested-With, Content-Type, Content-Length"
----

- Start ElasticSearch
[source.console]
----
terrence@muffler ~/elasticsearch
13:07:32 192 ğœ† docker run -d -v "$PWD/data":/usr/share/elasticsearch/data -v "$PWD/plugins":/usr/share/elasticsearch/plugins -p 9200:9200 -p 9300:9300 --name elasticsearch elasticsearch
----

- Start ElasticSearch (CORS enabled)
[source.console]
----
terrence@muffler ~/elasticsearch
13:07:32 192 ğœ† docker run -d -v "$PWD/data":/usr/share/elasticsearch/data -v "$PWD/plugins":/usr/share/elasticsearch/plugins -p 9200:9200 -p 9300:9300 --name elasticsearch elasticsearch
----

- Start Kibana
[source.console]
----
terrence@muffler ~/kibana
13:07:32 193 ğœ† docker run -d -v "$PWD/installedPlugins":/opt/kibana/installedPlugins --link elasticsearch:elasticsearch -p 5601:5601 --name kibana kibana
----

- Start ElasticSearch plugins
[source.console]
----
terrence@muffler ~/elasticsearch
13:07:32 194 ğœ† docker run -d -p 9100:9100 --name elasticsearch-head mobz/elasticsearch-head:5

13:07:32 195 ğœ† docker run -d -p 1358:1358 --name dejavu appbaseio/dejavu

13:07:32 196 ğœ† docker run -d -p 3030:3030 --name mirage appbaseio/mirage
----

- Log on ElasticSearch and Kibana container instances with SHELL
[source.console]
----
terrence@muffler ~
13:07:32 192 ğœ† docker exec -it elasticsearch /bin/bash

terrence@muffler ~
13:07:32 193 ğœ† docker exec -it kibana /bin/bash
----

- Visit ElsticSearch plugins
  * elasticsearch-head, http://localhost:9100
  * dejaVu, with app name / index (e.g. addresses) and connection URL http://localhost:9200 (without "/"), http://localhost:1358/live
  * mirage, with app name / index (e.g. addresses) and connection URL http://localhost:9200 (without "/"), http://localhost:3030
  * kopf (deprecated), http://localhost:9200/_plugin/kopf/

- Visit Kibana and its plugins
  * Kibana, http://0.0.0.0:5601/app/kibana
  * Sense, http://0.0.0.0:5601/app/sense - To avoid CORS in Sense plugin, ElasticSearch has to use hostname (muffler) of IP address (10.0.0.110), not localhost, e.g., http://muffler:9200/postaladdress/_search


References
----------
- ElaticSearch Docker image, https://hub.docker.com/_/elasticsearch/
- Kibana Docker image, https://hub.docker.com/_/kibana/
- ElasticSearch plugin *elasticsearch-head,* https://github.com/mobz/elasticsearch-head


Copying
-------
Copyright Â© 2016 - Terrence Miao. Free use of this software is granted under the terms of the GNU General Public License version 3 (GPLv3).
