Step by step run ElasticSearch / Kibana Docker images
=====================================================

This project including instructions to run ElasticSearch / Kibana Docker images on localhost.

- Create shared volumes / mounted directories
[source.console]
----
terrence@muffler ~/elasticsearch
13:07:32 189 ğœ† mkdir data config

iterrence@muffler ~/kibana
13:07:32 189 ğœ† mkdir installedPlugins
----

- Copy ALL exiting data, installed plugins from to shared, mounted directory
[source.console]
----
terrence@muffler ~/elasticsearch
13:07:32 190 ğœ† cp -a /usr/local/elasticsearch/data/* data

terrence@muffler ~/kibana
13:07:32 190 ğœ† cp -a /usr/local/kibana/installedPlugins/* installedPlugins

13:07:32 191 ğœ† ls -1 installedPlugins/
sense
----

- CORS (Cross Origin Resource Sharing)

To make sure you enable CORS settings for your ElasticSearch instance, for example ElasticSearch and UI both run on localhost, add the following lines into the ES configuration file - **config/elasticsearch.yml**

[source.console]
----
http.cors.enabled: true
http.cors.allow-origin: "/.*/"
http.cors.allow-credentials: true
http.cors.allow-headers: "Authorization, X-Requested-With, Content-Type, Content-Length"

terrence@muffler ~/elasticsearch
13:07:32 190 ğœ† ls -al config/
total 16
drwxr-xr-x  5 terrence  staff  170  4 Dec 16:30 .
drwxr-xr-x  5 terrence  staff  170  4 Dec 16:14 ..
-rw-r--r--@ 1 terrence  staff  347  4 Dec 16:30 elasticsearch.yml
-rw-r--r--  1 terrence  staff  272  4 Dec 16:27 log4j2.properties
drwxr-xr-x  2 terrence  staff   68  4 Dec 16:28 scripts

terrence@muffler ~/elasticsearch
13:07:32 190 ğœ† cat config/elasticsearch.yml

http.host: 0.0.0.0

# Uncomment the following lines for a production cluster deployment
#transport.host: 0.0.0.0
#discovery.zen.minimum_master_nodes: 1

## CORS enabled
http.cors.enabled: true
http.cors.allow-origin: "/.*/"
http.cors.allow-credentials: true
http.cors.allow-headers: "Authorization, X-Requested-With, Content-Type, Content-Length"

terrence@muffler ~/elasticsearch
13:07:32 190 ğœ† cat config/log4j2.properties
status = error

appender.console.type = Console
appender.console.name = console
appender.console.layout.type = PatternLayout
appender.console.layout.pattern = [%d{ISO8601}][%-5p][%-25c{1.}] %marker%m%n

rootLogger.level = info
rootLogger.appenderRef.console.ref = console
----

With CORS enabled in ElasticSearch, browser like Google Chrome DOESN'T need to have extension like _Allow-Control-Allow-Origin: *_ installed.

- Start ElasticSearch
[source.console]
----
terrence@muffler ~/elasticsearch
13:07:32 192 ğœ† docker run -d -v "$PWD/data":/usr/share/elasticsearch/data -v "$PWD/plugins":/usr/share/elasticsearch/plugins -p 9200:9200 -p 9300:9300 --name elasticsearch elasticsearch
----

- Start ElasticSearch (CORS enabled)
[source.console]
----
terrence@muffler ~/elasticsearch
13:07:32 192 ğœ† docker run -d -v "$PWD/data":/usr/share/elasticsearch/data -v "$PWD/plugins":/usr/share/elasticsearch/plugins -v "$PWD/config":/usr/share/elasticsearch/config -p 9200:9200 -p 9300:9300 --name elasticsearch elasticsearch
----

- Start Kibana
[source.console]
----
terrence@muffler ~/kibana
13:07:32 193 ğœ† docker run -d -v "$PWD/installedPlugins":/opt/kibana/installedPlugins --link elasticsearch:elasticsearch -p 5601:5601 --name kibana kibana
----

- Start ElasticSearch plugins (docker images)
[source.console]
----
terrence@muffler ~/elasticsearch
13:07:32 194 ğœ† docker run -d -p 9100:9100 --name elasticsearch-head mobz/elasticsearch-head:5

13:07:32 195 ğœ† docker run -d -p 1358:1358 --name dejavu appbaseio/dejavu

13:07:32 196 ğœ† docker run -d -p 3030:3030 --name mirage appbaseio/mirage
----

- Log on ElasticSearch and Kibana container instances with SHELL
[source.console]
----
terrence@muffler ~
13:07:32 192 ğœ† docker exec -it elasticsearch /bin/bash

terrence@muffler ~
13:07:32 193 ğœ† docker exec -it kibana /bin/bash
----

- Visit ElasticSearch plugins
  * elasticsearch-head, http://localhost:9100
  * dejaVu, with app name / index (e.g. addresses) and connection URL http://localhost:9200 (without "/"), http://localhost:1358/live
  * mirage, with app name / index (e.g. addresses) and connection URL http://localhost:9200 (without "/"), http://localhost:3030
  * kopf **(Deprecated)**, [blue yellow-background line-through]#http://localhost:9200/_plugin/kopf/#

- Visit Kibana and its plugins
  * Kibana, http://0.0.0.0:5601/app/kibana
  * Sense, http://0.0.0.0:5601/app/sense - To avoid CORS in Sense plugin, ElasticSearch has to use hostname (muffler) of IP address (10.0.0.110), not localhost, e.g., http://muffler:9200/postaladdress/_search


References
----------
- ElaticSearch Docker image, https://hub.docker.com/_/elasticsearch/
- Kibana Docker image, https://hub.docker.com/_/kibana/
- ElasticSearch plugin *elasticsearch-head,* https://github.com/mobz/elasticsearch-head


Copying
-------
Copyright Â© 2016 - Terrence Miao. Free use of this software is granted under the terms of the GNU General Public License version 3 (GPLv3).
