Step by step run ElasticSearch / Kibana Docker images
=====================================================

This project including instructions to run ElasticSearch / Kibana Docker images on localhost.

- Create shared volumes / mounted directories
[source.console]
----
terrence@muffler ~/elasticsearch
13:07:32 189 𝜆 mkdir data config

iterrence@muffler ~/kibana
13:07:32 189 𝜆 mkdir installedPlugins
----

- Copy ALL exiting data, installed plugins from to shared, mounted directory
[source.console]
----
terrence@muffler ~/elasticsearch
13:07:32 190 𝜆 cp -a /usr/local/elasticsearch/data/* data

terrence@muffler ~/kibana
13:07:32 190 𝜆 cp -a /usr/local/kibana/installedPlugins/* installedPlugins

13:07:32 191 𝜆 ls -1 installedPlugins/
sense
----

- CORS (Cross Origin Resource Sharing)

To make sure you **enable CORS** settings for your ElasticSearch instance, for example ElasticSearch and UI both run on localhost, add the following lines into the ES configuration file - **config/elasticsearch.yml**

[source.console]
----
http.cors.enabled: true
http.cors.allow-origin: "/.*/"
http.cors.allow-credentials: true
http.cors.allow-headers: "Authorization, X-Requested-With, Content-Type, Content-Length"

terrence@muffler ~/elasticsearch
13:07:32 190 𝜆 ls -al config/
total 16
drwxr-xr-x  5 terrence  staff  170  4 Dec 16:30 .
drwxr-xr-x  5 terrence  staff  170  4 Dec 16:14 ..
-rw-r--r--@ 1 terrence  staff  347  4 Dec 16:30 elasticsearch.yml
-rw-r--r--  1 terrence  staff  272  4 Dec 16:27 log4j2.properties
drwxr-xr-x  2 terrence  staff   68  4 Dec 16:28 scripts

terrence@muffler ~/elasticsearch
13:07:32 190 𝜆 cat config/elasticsearch.yml

http.host: 0.0.0.0

# Uncomment the following lines for a production cluster deployment
#transport.host: 0.0.0.0
#discovery.zen.minimum_master_nodes: 1

## CORS enabled
http.cors.enabled: true
http.cors.allow-origin: "/.*/"
http.cors.allow-credentials: true
http.cors.allow-headers: "Authorization, X-Requested-With, Content-Type, Content-Length"

terrence@muffler ~/elasticsearch
13:07:32 190 𝜆 cat config/log4j2.properties
status = error

appender.console.type = Console
appender.console.name = console
appender.console.layout.type = PatternLayout
appender.console.layout.pattern = [%d{ISO8601}][%-5p][%-25c{1.}] %marker%m%n

rootLogger.level = info
rootLogger.appenderRef.console.ref = console
----

With CORS enabled in ElasticSearch (5.x.x), browser like Google Chrome DOESN'T need to have extension installed like _Allow-Control-Allow-Origin: *_

ElaticSearch from version 6.x.x doesn't support Content-Type header [application/x-www-form-urlencoded]. You have to add Content-Type application/json to send a successful request to ElasticSearch.

NOTE: Due to ElasticSearch Head doesn't support ElasticSearch till version 5.x, you can check out "ElasticSearch Head" Chrome plugin at: https://chrome.google.com/webstore/detail/elasticsearch-head/ffmkiejjmecolpfloofpjologoblkegm which can run along with latest ElasticSearch and without needing of **CORS** setting enabled.

- Start ElasticSearch (5.x.x)
[source.console]
----
terrence@muffler ~/elasticsearch
13:07:32 192 𝜆 docker run -d -v "$PWD/data":/usr/share/elasticsearch/data -v "$PWD/plugins":/usr/share/elasticsearch/plugins -p 9200:9200 -p 9300:9300 --name elasticsearch elasticsearch
----

- Start ElasticSearch (5.x.x) with own configuration files
[source.console]
----
terrence@muffler ~/elasticsearch
13:07:32 192 𝜆 docker run -d -v "$PWD/data":/usr/share/elasticsearch/data -v "$PWD/plugins":/usr/share/elasticsearch/plugins -v "$PWD/config":/usr/share/elasticsearch/config -p 9200:9200 -p 9300:9300 --name elasticsearch elasticsearch
----

- Start Kibana (5.x.x)
[source.console]
----
terrence@muffler ~/kibana
13:07:32 193 𝜆 docker run -d -v "$PWD/installedPlugins":/opt/kibana/installedPlugins --link elasticsearch:elasticsearch -p 5601:5601 --name kibana kibana
----

- Start ElasticSearch (6.x.x) with data shared from old version ElasticSearch
[source.console]
----
terrence@muffler ~/elasticsearch
13:07:32 195 𝜆 docker run -d -v "$PWD/data":/usr/share/elasticsearch/data -p 9200:9200 -p 9300:9300 -e "discovery.type=single-node" --name elasticsearch6 docker.elastic.co/elasticsearch/elasticsearch:6.2.4
----

- Start Kibana (6.x.x)
[source.console]
----
terrence@muffler /Users/terrence
10:51:00 196 𝜆 docker run -d --link elasticsearch6:elasticsearch -p 5601:5601 --name kibana6 docker.elastic.co/kibana/kibana:6.2.4
----

- Start ElasticSearch plugins (docker images)
[source.console]
----
terrence@muffler ~/elasticsearch
13:07:32 194 𝜆 docker run -d -p 9100:9100 --name elasticsearch-head mobz/elasticsearch-head:5-alpine

13:07:32 195 𝜆 docker run -d -p 1358:1358 --name dejavu appbaseio/dejavu

13:07:32 196 𝜆 docker run -d -p 3030:3030 --name mirage appbaseio/mirage
----

- Log on ElasticSearch and Kibana container instances with SHELL
[source.console]
----
terrence@muffler ~
13:07:32 192 𝜆 docker exec -it elasticsearch /bin/bash

terrence@muffler ~
13:07:32 193 𝜆 docker exec -it kibana /bin/bash
----

- Visit ElasticSearch plugins
  * elasticsearch-head, http://localhost:9100
  * dejaVu, with app name / index (e.g. addresses) and connection URL http://localhost:9200 (without "/"), http://localhost:1358/live
  * mirage, with app name / index (e.g. addresses) and connection URL http://localhost:9200 (without "/"), http://localhost:3030
  * kopf **(Deprecated)**, [blue yellow-background line-through]#http://localhost:9200/_plugin/kopf/#

- Visit Kibana and its plugins
  * Kibana, http://0.0.0.0:5601/app/kibana
  * Sense, http://0.0.0.0:5601/app/sense - To avoid CORS in Sense plugin, ElasticSearch has to use hostname (muffler) of IP address (10.0.0.110), not localhost, e.g., http://muffler:9200/postaladdress/_search

Backup and Restore
------------------

Make sure ElasticSearch is bind to a network interface (not localhost, not 127.0.0.1). For example, **network.host: 10.101.32.53** in config/elasticsearch.yml file.

- Backup ElasticSearch Index's mapping and data to JSON files

[source.console]
----
𝜆 docker run --rm -ti -v /Users/terrence/elasticsearch/backup:/tmp taskrabbit/elasticsearch-dump --input=http://10.101.32.53:9200/location --output=/tmp/location-mapping.json --type=mapping
Mon, 04 Dec 2017 06:59:50 GMT | starting dump
Mon, 04 Dec 2017 06:59:50 GMT | got 1 objects from source elasticsearch (offset: 0)
Mon, 04 Dec 2017 06:59:50 GMT | sent 1 objects to destination file, wrote 1
Mon, 04 Dec 2017 06:59:50 GMT | got 0 objects from source elasticsearch (offset: 1)
Mon, 04 Dec 2017 06:59:50 GMT | Total Writes: 1
Mon, 04 Dec 2017 06:59:50 GMT | dump complete

𝜆 docker run --rm -ti -v /Users/terrence/elasticsearch/backup:/tmp taskrabbit/elasticsearch-dump --input=http://10.101.32.53:9200/location --output=/tmp/location.json --type=data --limit=10000
Mon, 04 Dec 2017 07:07:12 GMT | starting dump
Mon, 04 Dec 2017 07:07:12 GMT | got 10000 objects from source elasticsearch (offset: 0)
Mon, 04 Dec 2017 07:07:13 GMT | sent 10000 objects to destination file, wrote 10000
Mon, 04 Dec 2017 07:07:13 GMT | got 10000 objects from source elasticsearch (offset: 10000)
Mon, 04 Dec 2017 07:07:13 GMT | sent 10000 objects to destination file, wrote 10000
Mon, 04 Dec 2017 07:07:13 GMT | got 1348 objects from source elasticsearch (offset: 20000)
Mon, 04 Dec 2017 07:07:13 GMT | sent 1348 objects to destination file, wrote 1348
Mon, 04 Dec 2017 07:07:13 GMT | got 0 objects from source elasticsearch (offset: 21348)
Mon, 04 Dec 2017 07:07:13 GMT | Total Writes: 21348
Mon, 04 Dec 2017 07:07:13 GMT | dump complete

...

𝜆 docker run --rm -ti -v /Users/terrence/elasticsearch/backup:/tmp taskrabbit/elasticsearch-dump --input=http://10.101.32.53:9200/postaladdress --output=/tmp/postaladdress-mapping.json --type=mapping

𝜆 docker run --rm -ti -v /Users/terrence/elasticsearch/backup:/tmp taskrabbit/elasticsearch-dump --input=http://10.101.32.53:9200/postaladdress --output=/tmp/postaladdress.json --type=data --limit=100000
----

- Restore Index's mapping and data JSON data to ElasticSearch

[source.console]
----
𝜆 docker run --rm -ti -v /Users/terrence/elasticsearch/backup:/tmp taskrabbit/elasticsearch-dump --input=/tmp/location-mapping.json --output=http://10.101.32.53:9200/location --type=mapping
Mon, 04 Dec 2017 07:46:13 GMT | starting dump
Mon, 04 Dec 2017 07:46:13 GMT | got 1 objects from source file (offset: 0)
Mon, 04 Dec 2017 07:46:13 GMT | sent 1 objects to destination elasticsearch, wrote 2
Mon, 04 Dec 2017 07:46:13 GMT | got 0 objects from source file (offset: 1)
Mon, 04 Dec 2017 07:46:13 GMT | Total Writes: 2
Mon, 04 Dec 2017 07:46:13 GMT | dump complete

𝜆 docker run --rm -ti -v /Users/terrence/elasticsearch/backup:/tmp taskrabbit/elasticsearch-dump --input=/tmp/location.json --output=http://10.101.32.53:9200/location --type=data --limit=10000
Mon, 04 Dec 2017 07:50:24 GMT | starting dump
Mon, 04 Dec 2017 07:50:25 GMT | got 10000 objects from source file (offset: 0)
Mon, 04 Dec 2017 07:50:27 GMT | sent 10000 objects to destination elasticsearch, wrote 10000
Mon, 04 Dec 2017 07:50:27 GMT | got 10057 objects from source file (offset: 10000)
Mon, 04 Dec 2017 07:50:28 GMT | sent 10057 objects to destination elasticsearch, wrote 10057
Mon, 04 Dec 2017 07:50:28 GMT | got 1291 objects from source file (offset: 20057)
Mon, 04 Dec 2017 07:50:28 GMT | sent 1291 objects to destination elasticsearch, wrote 1291
Mon, 04 Dec 2017 07:50:28 GMT | got 0 objects from source file (offset: 21348)
Mon, 04 Dec 2017 07:50:28 GMT | Total Writes: 21348
Mon, 04 Dec 2017 07:50:28 GMT | dump complete

...

𝜆 docker run --rm -ti -v /Users/terrence/elasticsearch/backup:/tmp taskrabbit/elasticsearch-dump --input=/tmp/postaladdress-mapping.json --output=http://10.101.32.53:9200/postaladdress --type=mapping

𝜆 docker run --rm -ti -v /Users/terrence/elasticsearch/backup:/tmp taskrabbit/elasticsearch-dump --input=/tmp/postaladdress.json --output=http://10.101.32.53:9200/postaladdress --type=data --limit=100000
----

References
----------
- ElaticSearch Docker image, https://hub.docker.com/_/elasticsearch/
- Kibana Docker image, https://hub.docker.com/_/kibana/
- ElasticSearch plugin *elasticsearch-head,* https://github.com/mobz/elasticsearch-head


Copying
-------
Copyright © 2016 - Terrence Miao. Free use of this software is granted under the terms of the GNU General Public License version 3 (GPLv3).
